Fixing pre-commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,3 +1,12 @@
 #!/bin/bash
 
-return npm run test
+npm run test 2> /dev/null
+
+
+if [ $? -eq 0 ]
+then
+exit 0
+else
+echo "[!] Aborting commit due to failing tests."
+exit 1
+fi
